#!/usr/bin/python3
from sys import argv

with open(argv[1]) as x:
    for line in x:
        number = int(line)
        print("{:d}=".format(number), end='')
        if number % 2 == 0:
            print("{}*2".format(number//2))
            continue
        for k in range(3, number, 2):
            if number % k == 0:
                factors = number//k
                for l in range(3, factors, 2):
                    if factors % l == 0 or l == 0:
                        break
                print("{}*{}".format(factors, k))
                break
